# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - gyschatbot-frontend-production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: bun install
        run: |
          bun install
          bun run build

      - name: Prepare artifact for deployment job
        run: |
          mkdir -p ./standalone
          cp -R ./.next/standalone ./
          cp -R ./public ./standalone/public
          cp -R ./.next/static ./standalone/.next
          rm -rf ./standalone/.env
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gyschatbot-frontend-production'
          slot-name: 'Production'
          package: './standalone'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F45C1B526E83428EBE1350784061C288 }}